name: pm25_schwartz_2017_2020
channels:
  - conda-forge
dependencies:
  - python=3.11
  - snakemake-minimal
  - hydra-core
  - omegaconf
  - numpy
  - pandas
  - geopandas
  - rasterio
  - rioxarray
  - xarray
  - pyproj
  - shapely
  - scipy
  - pyarrow
  - tqdm
  - pip
  - pip:
      - pytest
