base_path: data

dirs:
  raw:
    daily: null
    monthly: null
    yearly: null
    shapefiles: null
  input:
    daily: null
    monthly: null
    yearly: null
    shapefiles: null
  intermediate:
    daily: null
    monthly: null
    yearly: null
  output:
    daily: null
    monthly: null
    yearly: null
