base_path: data

dirs:
  raw:
    grids:
      daily: null
      monthly: null
      yearly: null
    polygons: null
  input:
    grids:
      daily: null
      monthly: null
      yearly: null
    polygons: null
  intermediate:
    daily: null
    monthly: null
    yearly: null
  output:
    daily: null
    monthly: null
    yearly: null
